version: '3'

services:
  postgres:
    restart: always
    image: postgres
    ports:
      - 5432:5432
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: cstag
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    ports:
      - 9200:9200
    networks:
      - backend
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - search-data:/usr/share/elasticsearch/data
    mem_limit: 3072M

  kibana:
    restart: always
    image: docker.elastic.co/kibana/kibana:7.11.1
    environment:
      - ELASTICSEARCH_HOSTS=http://192.168.0.10:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  rabbit:
    restart: always
    image: rabbitmq:3-management
    hostname: rabbit-master
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - backend
    volumes:
      - rabbit-data:/var/lib/rabbitmq

volumes:
  postgres-data:
  search-data:
  rabbit-data:

networks: 
  backend: