version: '3'

services:
  postgres:
    restart: always
    image: postgres
    ports:
      - 5432:5432
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: cstag
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  meilisearch:
    restart: always
    image: getmeili/meilisearch:v0.18.1
    ports:
      - 7700:7700
    networks: 
      - backend
    volumes:
      - search-data:/data.ms

  rabbit:
    restart: always
    image: rabbitmq:3-management
    hostname: rabbit-master
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - backend
    volumes:
      - rabbit-data:/var/lib/rabbitmq

volumes:
  postgres-data:
  search-data:
  rabbit-data:

networks: 
  backend: