FROM node:lts-alpine AS intermediate
WORKDIR /tmp
COPY services/event_consumer/package*.json ./services/event_consumer/
WORKDIR /tmp/services/event_consumer
RUN npm ci --only-production --no-optional

FROM node:lts-alpine
USER node
WORKDIR /app
COPY services/event_consumer/package*.json ./services/event_consumer/
COPY --from=intermediate /tmp/services/event_consumer/node_modules ./services/event_consumer/node_modules
COPY services/event_consumer/src ./services/event_consumer/src
WORKDIR /app/services/event_consumer
CMD ["node", "./src/index.js"]
