package br.com.cstag.core.entities

data class ArtespCategory(
    val id: Int,
    val name: String
) {
    companion object {
        val list = listOf(
            ArtespCategory(id = 1, name = "2 eixos, rodagem simples"),
            ArtespCategory(id = 2, name = "2 eixos, rodagem dupla"),
            ArtespCategory(id = 3, name = "3 eixos, rodagem dupla"),
            ArtespCategory(id = 4, name = "4 eixos, rodagem dupla"),
            ArtespCategory(id = 5, name = "5 eixos, rodagem dupla"),
            ArtespCategory(id = 6, name = "6 eixos, rodagem dupla"),
            ArtespCategory(id = 7, name = "3 eixos, rodagem simples"),
            ArtespCategory(id = 8, name = "4 eixos, rodagem simples"),
            ArtespCategory(id = 16, name = "16 eixos, rodagem dupla"),
            ArtespCategory(id = 17, name = "17 eixos, rodagem dupla"),
            ArtespCategory(id = 18, name = "18 eixos, rodagem dupla"),
            ArtespCategory(id = 19, name = "19 eixos, rodagem dupla"),
            ArtespCategory(id = 20, name = "20 eixos, rodagem dupla"),
            ArtespCategory(id = 21, name = "21 eixos, rodagem dupla"),
            ArtespCategory(id = 22, name = "22 eixos, rodagem dupla"),
            ArtespCategory(id = 23, name = "23 eixos, rodagem dupla"),
            ArtespCategory(id = 24, name = "24 eixos, rodagem dupla"),
            ArtespCategory(id = 25, name = "25 eixos, rodagem dupla"),
            ArtespCategory(id = 26, name = "26 eixos, rodagem dupla"),
            ArtespCategory(id = 27, name = "27 eixos, rodagem dupla"),
            ArtespCategory(id = 28, name = "28 eixos, rodagem dupla"),
            ArtespCategory(id = 29, name = "29 eixos, rodagem dupla"),
            ArtespCategory(id = 30, name = "30 eixos, rodagem dupla"),
            ArtespCategory(id = 31, name = "31 eixos, rodagem dupla"),
            ArtespCategory(id = 32, name = "32 eixos, rodagem dupla"),
            ArtespCategory(id = 33, name = "33 eixos, rodagem dupla"),
            ArtespCategory(id = 34, name = "34 eixos, rodagem dupla"),
            ArtespCategory(id = 35, name = "35 eixos, rodagem dupla"),
            ArtespCategory(id = 36, name = "36 eixos, rodagem dupla"),
            ArtespCategory(id = 37, name = "37 eixos, rodagem dupla"),
            ArtespCategory(id = 38, name = "38 eixos, rodagem dupla"),
            ArtespCategory(id = 39, name = "39 eixos, rodagem dupla"),
            ArtespCategory(id = 40, name = "40 eixos, rodagem dupla"),
            ArtespCategory(id = 41, name = "41 eixos, rodagem dupla"),
            ArtespCategory(id = 42, name = "42 eixos, rodagem dupla"),
            ArtespCategory(id = 43, name = "43 eixos, rodagem dupla"),
            ArtespCategory(id = 44, name = "44 eixos, rodagem dupla"),
            ArtespCategory(id = 45, name = "45 eixos, rodagem dupla"),
            ArtespCategory(id = 46, name = "46 eixos, rodagem dupla"),
            ArtespCategory(id = 47, name = "47 eixos, rodagem dupla"),
            ArtespCategory(id = 48, name = "48 eixos, rodagem dupla"),
            ArtespCategory(id = 61, name = "7 eixos, rodagem dupla"),
            ArtespCategory(id = 62, name = "8 eixos, rodagem dupla"),
            ArtespCategory(id = 63, name = "9 eixos, rodagem dupla"),
            ArtespCategory(id = 64, name = "10 eixos, rodagem dupla"),
            ArtespCategory(id = 65, name = "11 eixos, rodagem dupla"),
            ArtespCategory(id = 66, name = "12 eixos, rodagem dupla"),
            ArtespCategory(id = 67, name = "13 eixos, rodagem dupla"),
            ArtespCategory(id = 68, name = "14 eixos, rodagem dupla"),
            ArtespCategory(id = 69, name = "15 eixos, rodagem dupla"),
        )
    }
}